### ISSUE TITLE
Can't open Zotero from Desktop

### ISSUE THREAD

**Issue by arvchi** [smathot/zotero_installer#4]
Thanks for the installer. I used your code to add the PPA and installed Zotero from the Terminal in Ubuntu 16.04 (in VirtualBox). Seems I can only open Zotero by typing "zotero" in the terminal, and if I close the Terminal the app shuts down. I cannot find the Zotero app when I search for it in the Unity Launcher.

All help appreciated.

**Comment by smathot** [comment]
My first guess is that Unity hasn't refreshed yet. This sometimes takes a long time. So I would first make sure that it's not simply that.

If not, you can re-run the installation from the terminal:

~~~
sudo apt-get remove zotero-standalone # first unintstall
sudo apt-get install zotero-standalone
~~~

This should show you all steps of the installation script, and also any errors that occur.

**Comment by arvchi** [comment]
You are right, Unity was not refreshed. No actions were needed.
