### ISSUE TITLE
Update needed as 5.0.11 has a security bug and is thus offline

### ISSUE THREAD

**Issue by StianOby** [smathot/zotero_installer#6]
See https://forums.zotero.org/discussion/comment/284109/#Comment_284109

**Comment by StianOby** [comment]
Here is a pull request: https://github.com/smathot/zotero_installer/pull/7

**Comment by smathot** [comment]
Thanks for pointing this out. I just pushed 5.0.17. (I closed your pull request because it was for 5.0.17, and also didn't modify all necessary files.)
